### ISSUE TITLE
I cant find the place where the help command is made?

### ISSUE THREAD

**Issue by sqeezyjs** [Ded-Ex/Klaus-Bot#1]
Where is the help command located? I cant find it.. I would be grate if someone can help but thanks anyways

**Comment by Ded-Ex** [comment]
Hey squeezyjs,
Just saw your email from my website contact form. Thanks!

In regards to the help command, it is an already integrated feature of the discord.py library which I have not adjusted. It simply autogenerates a list of all the commands therefore I have written no actual code for it.

If you'd like help, you can overwrite the command by creating a new help command which I am able to help you with.
Final question: what are you translating this into? (just for personal interest)

**Comment by sqeezyjs** [comment]
Oh ok Thanks i had a solution for this problem but there is another big problem..


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 942, in on_message
    await self.process_commands(message)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 939, in process_commands
    await self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 856, in invoke
    await self.prepare(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 790, in prepare
    await self._parse_arguments(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 693, in _parse_arguments
    raise discord.ClientException(fmt.format(self))
discord.errors.ClientException: Callback for announce command is missing "ctx" parameter.



I am getting this error can you help?

**Comment by sqeezyjs** [comment]
Hello Thanks for the reply, i am translating  it to German.. 

I have another Problem when i do a announce then it only sends 1 word.. EXAMPLE: I say !announcemessage 1 2 3 4 but it only writes the 1 how can i fix it?

**Comment by Ded-Ex** [comment]
Sorry for the late response again - if needed contact me via email on my profile page as I'll probably reach that quicker or via Discord.

I'm not really sure why that is happening. The command works by first writing !announcetitle with a title, then !announcemessage with a message and then sends the announcement via the !announce command. This is strange. Can you send me an output of the discord channel where you are typing these?

**Comment by Ded-Ex** [comment]
Hey,

I haven't heard anything as of now so I'm going to assume the issue is fixed or you are no longer continuing so I shall close this issue in 2 days if I do not hear from you

Thanks
