### ISSUE TITLE
what do i do after i made a new command in cogs

### ISSUE THREAD

**Issue by RayKKGames** [Ded-Ex/Klaus-Bot#2]

**Comment by Ded-Ex** [comment]
Hi,

I'm happy to help on what's happening.

Would you be able to share exactly what you've done and want to achieve so I can help you through it?

Thanks

**Comment by RayKKGames** [comment]
I Tried To Make A Mute Command Since The Bot Does Not Have A Mute Command 

But After I Enter My Code In Moderation.py, I started to ran my bot and then I got a error on discordbot.py this is the line that got the error : client.load_extension(f'cogs.{filename[:-3]}')

**Comment by RayKKGames** [comment]
How Long Does It Take To Respond??

**Comment by Ded-Ex** [comment]
Hmmm, that shouldn't be happening. As long as the command is written in the moderation.py file it should successfully load.

Have you definitely used the correct syntax?

In order for me to find the fix, would it be possible for you to send the code or a link to a repo with your fork?

Thanks

**Comment by Ded-Ex** [comment]
I'm also happy to write a tempmute command, just explain exactly how it needs to function.

**Comment by RayKKGames** [comment]
Hello Sorry For The Slow Respond Heres The Mute Code 
`@client.command()
@commands.has_role("Mod")
async def mute(ctx, user : discord.Member, duration = 0,*, unit = None):
    roleobject = discord.utils.get(ctx.message.guild.roles, id=730016083871793163)
    await ctx.send(f":white_check_mark: Muted {user} for {duration}{unit}")
    await user.add_roles(roleobject)
    if unit == "s":
        wait = 1 * duration
        time.sleep(wait)
    elif unit == "m":
        wait = 60 * duration
        time.sleep(wait)
    await user.remove_roles(roleobject)
    await ctx.send(f":white_check_mark: {user} was unmuted")`
    
    And Sorry I'm New To Python Coding What Do You Mean To Explain Exactly How It Needs To Function.
    
    Also Do You Know Any Course For Python???

**Comment by RayKKGames** [comment]
Hi

**Comment by Ded-Ex** [comment]
Hey,

The command itself seems fine to me (sorry for the late response I'm in hospital rn as I've been dealing with something for a couple days).

Are you definitely placing it in the correct place within moderation.py (indented in the class and below the loading of the cogs)

Thanks

**Comment by RayKKGames** [comment]
I'm so sorry to hear that, sorry for being impatient And What Do You Mean By Indented In The Class And Below The Loading Of The Cogs ( Sorry I Just Started Three Days Ago And Don't Know Why You Mean I am a little stupidd

Under This: `    @commands.Cog.listener()
    async def on_ready(self):
      print('Moderation Online!')`

Or Under This??
`def setup(client):
    client.add_cog(Moderation(client))`

**Comment by Ded-Ex** [comment]
Yes, underneath @commands.Cog.listener() async def on_ready(self): print('Moderation Online!')

That's where the command should go. Did you put it there?

**Comment by RayKKGames** [comment]
Yeah I did with all the other commands you put

**Comment by Ded-Ex** [comment]
Hmm that's weird. If possible, send me a GitHub gist (copy your moderation.py code into this) so I can take a look.

Thanks

**Comment by RayKKGames** [comment]
Ok 

Here You Go : https://gist.github.com/RayKKGames/d4f41abb8679f537d2801107b102bf0f

**Comment by Ded-Ex** [comment]
Hey Ray, I've had a look at the code.
It seems fine but I'm thinking there may be a problem with my program and changes to the Discord API that I have not reflected in my code.

Sorry for the inconvenience this has caused but as of current I do not intent to affect this.

Feel free to get in touch if you want any help with places and things to learn Python and Discord.py as I'm happy to help but sorry about the code.

Thanks

**Comment by RayKKGames** [comment]
Ok Do You Know How To Get Started Learning Python??
Because I Really Need Help With That Cause I Have No Idea What I'm Doing
So Please Help

Thanks

**Comment by Ded-Ex** [comment]
Okay, that's cool.

I'd recommend starting with a website like https://www.w3schools.com/python/default.asp to learn the basics. Go through each step, make notes and try it out in IDLE aswell. If something doesn't make sense, look into it further as it will only help you.

From there you need to start applying these skills. Something like the tasks in this guide https://computersciencewiki.org/images/b/b1/Programming_companion_Python.pdf here are useful for applying skills in tasks that get increasingly harder. Have a go at that.

Finally, aim to create a project (e.g. a discord bot). It doesn't have to be anything special and feel free to use YouTube all you need but this will help you gain an understanding of what is needed to complete a full project.

If there are any questions, 99/100 times https://stackoverflow.com/ will have the answer.

Good luck and feel free to contact!

**Comment by RayKKGames** [comment]
Thx Do You Have A Youtube Channel??

**Comment by Ded-Ex** [comment]
Hi,
Sorry I don't have a YT channel personally. As for my discord, my username is Cole_Ricketts#9365 so just send me a friend request.

One final point I should mention, there are great Discord communities for all things like the Python and Discord.py discord with people for 24/7 help

**Comment by RayKKGames** [comment]
Alright Thx I'll Contact You On Discord Then
