### ISSUE TITLE
warn

### ISSUE THREAD

**Issue by Hris000** [Ded-Ex/Klaus-Bot#3]
you didnt set a guild id into the database, so if my bot is in another server i have the same warnings as in the other one.

**Comment by Ded-Ex** [comment]
Do you have the bot in more than one server then?

**Comment by Hris000** [comment]
> Right got it, are you proficient enough to edit this in the code and submit a request?
> 
> Otherwise say so and I will look.

Uh, i will try because i didnt do much with databases

**Comment by Ded-Ex** [comment]
Sure, contact me if help is needed

**Comment by Hris000** [comment]
> Sure, contact me if help is needed

okay nice

**Comment by Hris000** [comment]
> Sure, contact me if help is needed

so i have this problem when i warn someone it creates multiple values for the same guild and another issue when i warn someone it only shows that i warned him 1 time

**Comment by Ded-Ex** [comment]
Errr right, seems to be a problem at the database end I suppose then. I think the way I have designed it is so that it will work purely with one guild. I have not considered other variables which could affect this and I believe this would have to be a big patch.

**Comment by Hris000** [comment]
> Errr right, seems to be a problem at the database end I suppose then. I think the way I have designed it is so that it will work purely with one guild. I have not considered other variables which could affect this and I believe this would have to be a big patch.

mhh okay, so i fixed it now that i can warn more than 1 time

**Comment by Ded-Ex** [comment]
Okay cool, that works well
